---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falcon.fullname" . }}
  labels:
    {{- include "falcon.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "files/configs/*").AsConfig | nindent 2 }}
