apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon.fullname" . }}
  labels:
    {{- include "falcon.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
