version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  app:
    image: bulbawarrior/falcon:latest
    ports:
      - "80:8000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-file: "5"
        max-size: "10m"
