version: "3"

networks:
  loki:

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-file: "5"
    max-size: "10m"

x-deploy:
  &deploy
  resources:
    limits:
      memory: "512M"


services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging: *default-logging
    deploy: *deploy

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging: *default-logging
    deploy: *deploy

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging: *default-logging
    deploy: *deploy

  app:
    image: bulbawarrior/falcon:latest
    ports:
      - "80:8000"
    networks:
      - loki
    logging: *default-logging
    deploy: *deploy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/config.yml"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    networks:
      - loki
    logging: *default-logging
    deploy: *deploy
