password: ENC[AES256_GCM,data:iGB4bnjUWzUy0BQ=,iv:9PWqU0er1xxZNK5WKXw4F9FQ5/nSKblIUK4tqHMmmcI=,tag:Lpr4coQJ7rJ9GKour70/Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-25T11:25:09Z"
    mac: ENC[AES256_GCM,data:1CGQ3cT8M+Vk4n3DlVCT+j/vsAwFWlswhmyaTHPJUQMQg6bTYaCnSVj5RBnyJbErhZlIRCajjq2BEY3zY++hAGdfr9Y4dS9aiXv+w1ytf9cDuQlsFFzo9U6NSV1purDYSne0EF3GVD0II3cwu8sqAw79vpEz1EViuK2930pjV8E=,iv:uUSAItBszNLCOrk3hVmTcgk8IU0z0aLUlvTau2DAtFg=,tag:TVDgQettmB9XSnLupAJwYw==,type:str]
    pgp:
        - created_at: "2021-09-25T11:24:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2k7MvpXz55tAQ//TWmkuskCxgCpMYz4ZFDM4r9U8RPd2IF+rdAgoLo65A2S
            sd3FeyM5zyipAo72Yv4OdXADNX/lbDLncgBk7a6AmrwLpEukpPn4cjn/BGSiHLZ0
            tX+QHcxNlGZbKbDBG1PEV3mW4HcWanlNoHCJlPsTzA6WEpVh7DdbOa15+gAm7vCJ
            F9bRlXEDJjoexo6DeGVZgl9RvbDjEtQ2MoqckOYhO5K2mujGqJlyzUcVnfZMRNpx
            nkGk4OxGrBB4rm78nMFBRYKSdykg9+N7P7kznY7oNKmle+BDGIB/C9ktqv3ON1A0
            F4kSBLZiQATP+Z5bmbcIQFI2I0bYAqzm0aOmS6FznRW1KbEKgv0u3GUqpvw9ATzV
            r7DEFPRWnJrQH7WGMVNCYcF8MOe3cX+3UCB6BSvpi0W3BA7h3k5+rr4TzC7Hx+c+
            CvmjpQK2hD7gHj7wgvfzCe223iEF3e8APWPz93NHsHMQbXPQ/ogG6ssvyAKnPpvB
            /I1xLRSRNZuxHXO8VybOV5N/79BVIQs7nAkHkddRu2RSBWe5A7UAOVv3JzLLBZRI
            hlPoVWfSI6e9zRlgxxKqkzj2bY0aqxQNh5ehBHbeX/B1MKp4+baCX9YOv/cnydYt
            Iij6YOog+bDuMjhYSKlGfPtmk8l14XUpwWO6k1CxSds5w9mOqAHPL9nS8myFgUzS
            XgHuW/4N9tMGrh9089UzQsOklJZm0hiItnJ9Cbr5E6ZLgqvsAgPxQdiFo/06oCLa
            TDzxat7CGHV6udKU+jYNPpejk4JkCHNK57aZRCmeai6QJbG/04BZVpnK/88YH88=
            =ph5v
            -----END PGP MESSAGE-----
          fp: 045A99E1F54CD6E1FB25A0991AE21D249B6124E7
    unencrypted_suffix: _unencrypted
    version: 3.7.1
