global:
  scrape_interval: 15s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "loki"
    scrape_interval: 5s
    static_configs:
      - targets:
          - loki:3100
